urbit/bridge

package-lock.json
package.json
src/Bridge.js
src/components/Base.js
src/components/UploadButton.js
src/lib/error.js
src/lib/router.js
src/lib/wallet.js
src/style/extend.css
src/views/AcceptTransfer.js
src/views/CancelTransfer.js
src/views/CreateGalaxy.js
src/views/GenKeyfile.js
src/views/IssueChild.js
src/views/Keystore.js
src/views/Ledger.js
src/views/Mnemonic.js
src/views/PrivateKey.js
src/views/SetKeys.js
src/views/SetProxy.js
src/views/Shards.js
src/views/Ticket.js
src/views/Transfer.js
src/views/Trezor.js
src/views/ViewPoint.js
src/views/Wallet.js

Resolves #8.
Adds support for authenticating via Ethereum keystore files (w/password) and raw Ethereum private keys.

Additional authentication methods

---

package.json
src/components/StatelessTransaction.js
src/lib/ledger.js
src/lib/txn.js
src/views/AcceptTransfer.js

I wound up cleaning up `StatelessTransaction` a fair bit while trying to reproduce a bug, enough that it's worth merging in.
Some other miscellaneous cleanup in there as well.  In particular, importing specifically the `Nothing` and `Just` constructors from `folktale/maybe` makes code involving that library a lot less verbose.

Clean up StatelessTransaction

---

src/components/Header.js
src/components/StatelessTransaction.js
src/lib/router.js
src/style/extend.css
src/style/input.css
src/views/Ticket.js

Fixed several UI issues on the Urbit Ticket screen. 
I used the spinner from the send-txn-spinner branch, so this PR supercedes https://github.com/urbit/bridge/pull/68

Ticket ui fixes

---

src/Bridge.js
src/views/Network.js

Use secure connection for WebSockets

---

src/components/StatelessTransaction.js
src/style/button.css
src/style/extend.css
src/views/AcceptTransfer.js
src/views/CancelTransfer.js
src/views/CreateGalaxy.js
src/views/IssueChild.js
src/views/SetKeys.js
src/views/SetProxy.js
src/views/Transfer.js

Left it with the default styling for now.

Range slider for gas price

---

package.json
src/views/Trezor.js
src/views/Wallet.js

This makes it compatible with latest Trezor firmware.
Also took the liberty of re-enabling Trezor support in offline mode.

Use latest Trezor Connect

---

src/components/PointList.js
src/views/Points.js

Add loading placeholder text for points

---

package-lock.json
src/bridge/lib/wallet.js
src/bridge/views/Mnemonic.js
src/bridge/views/Shards.js
src/bridge/views/Ticket.js

(Resolves #3)
Adds optional passphrase inputs to the appropriate auth views (ticket, shards, mnemonic).

Support optional BIP39 passphrases

---

src/Root.js
src/bridge/views/GenKeyfile.js
src/bridge/views/Point/Actions.js
src/bridge/views/SetKeys.js

There are still a couple remaining, though fixing them is marginally more involved than gutting dead code (which is all I've done here).

Fix most ESLint warnings.

---

src/bridge/components/InnerLabelDropdown.js
src/bridge/components/StatelessTransaction.js
src/bridge/style/extend.css
src/bridge/views/Network.js
src/bridge/views/Wallet.js

Supports https://github.com/urbit/bridge/issues/75

Add chain ID dropdown + custom chain ID input

---

src/bridge/Bridge.js

Use vanilla websockets when in development.

---

package-lock.json
package.json

I've tested all the transactions on localnode, and everything seems to work as expected. 
Addresses https://github.com/urbit/bridge/issues/101

Update Web3 to latest beta version (beta.33 to beta.52)

---

src/bridge/components/StatelessTransaction.js

Fixes https://github.com/urbit/bridge/issues/111

add defaults for nonce and chainId, and clear signed transaction

---

src/bridge/components/ReactSVGComponents.js

Removes annoying console errors.

Fix missing key props on sigil ReactSVGComponents

---

README.md

Looking at this a day later, felt like it could be further improved

Clarify instructions in README

---

src/bridge/views/IssueChild.js

Closes #121 
Tear me apart boys.

Add autocomplete to IssueChild

---

src/bridge/views/Point/Actions.js
src/bridge/views/Points.js

Update wording around key configuration

---

src/Root.js
src/walletgen/Walletgen.js
src/walletgen/index.js

this PR imports the walletgen styles and uses the existing mechanism of enabling/disabling the respective stylesheets for each app view.

import walletgen styles for walletgen appview

---

src/bridge/components/InnerLabelDropdown.js
src/bridge/components/PointList.js
src/walletgen/components/Header.js

adding keys to things as I discover them

fix react key warnings

---

src/bridge/Bridge.js
src/bridge/components/DropdownItem.js
src/bridge/components/HorizontalSelector.js
src/bridge/components/Passport.js
src/bridge/components/StatelessTransaction.js
src/bridge/components/icons/Chevron.js
src/bridge/views/InviteTicket.js
src/bridge/views/InvitesSend.js
src/bridge/views/Ledger.js
src/bridge/views/Network.js
src/bridge/views/SetKeys.js
src/bridge/views/Ticket.js
src/bridge/views/Trezor.js
src/bridge/views/Wallet.js
src/walletgen/views/Generate.js

these files seem to have escaped formatting, so I ran `npm run lint:fix` on them

fix: reformat files

---

src/bridge/Bridge.js
src/bridge/components/Header.js
src/bridge/components/PointList.js
src/bridge/lib/router.js
src/bridge/store/pointCache.js
src/bridge/store/pointCursor.js
src/bridge/views/AcceptTransfer.js
src/bridge/views/CancelTransfer.js
src/bridge/views/GenKeyfile.js
src/bridge/views/InvitesManage.js
src/bridge/views/InvitesSend.js
src/bridge/views/IssueChild.js
src/bridge/views/Point.js
src/bridge/views/Points.js
src/bridge/views/SentTransaction.js
src/bridge/views/SetKeys.js
src/bridge/views/SetProxy.js
src/bridge/views/Transfer.js
src/bridge/views/ViewPoint.js

similar to the previous: move the point cursor and point cache into a context store

Extract point cursor & point cache

---

src/bridge/views/Point/Actions.js

Don't let planets set spawn proxies

---

package-lock.json
package.json

update urbit-ob to 4.0 to include that patp fix

deps: update urbit-ob to 4.0.1 to include patp fix

---

src/bridge/Bridge.js
src/bridge/components/StatelessTransaction.js
src/bridge/store/txnCursor.js
src/bridge/views/SentTransaction.js

the final one! moving the txn cursor into its own container

Extract txcursor

---

src/lib/useIsEclipticOwner.js
src/store/lib/usePointStore.js

fix: correctly include ecliptic owner logic

---

config-overrides.js
package-lock.json
package.json
src/Bridge.js
src/index.js

title explains: following the new api from https://github.com/cdharris/react-app-rewire-hot-loader and https://github.com/gaearon/react-hot-loader to get better hooks support - looking 👌 to me

feat: upgrade to latest hotreload api and add better hook support

---

src/lib/constants.js
src/lib/contracts.js
src/store/lib/useInvitesStore.js
src/store/lib/useRekeyDateStore.js

Straightforward one here!
closes #185

Fix rekey date issue, add contract address

---

src/lib/usePermissionsForPoint.js
src/views/Admin/AdminEditPermissions.js
src/views/Point.js

@shrugs Went ahead and did some small bits of work here, mostly dealing with making UI match chain logic. Hope this doesn't overlap with anything un-pushed!
(A little bit unsure about my `useMemo` usage. Had `availableInvites` fetching in there as well at first, (we really only want to do that in the planet case), but hooks in callbacks are invalid. Maybe this should just be an anonymous function call now instead.)

indigo-admin helper

---

src/lib/useImpliedTicket.js
src/views/Activate/ActivateCode.js
src/views/Landing.js

Deduces the ticket from the url#hash so that we can pre-fill the field in the invite activation flow.* Also auto-navigates to login or activation if a point or invite ticket are implied respectively.
\* We may or may not want to do slightly more sophisticated ticket-in-url formatting at some point.

Implied ticket & navigation

---

src/lib/txn.js
src/views/Activate/ActivateCode.js

Small unhappy-path fixes

---

src/lib/constants.js
src/lib/useEthereumTransaction.js
src/lib/usePermissionsForPoint.js
src/views/Point.js

See commit messages. I'm going to need a drink after hunting down that async tx builder one. (^:

Spawn perms, async tx building, set proxy gas limit

---

DEVELOPMENT.md
README.md

As approved by @alexmatz out of band. Will go and merge, but happy to still take comments on this.

Update readme for new release

---

src/Bridge.js
src/views/Activate.js
src/views/Activate/ActivateCode.js

Moves it to before the "download passport" step.
Still displays it prior to login.

Don't display disclaimer prior to activation code use

---

src/views/Admin/AdminNetworkingKeys.js
src/views/Admin/AdminTransfer.js
src/views/Login.js
src/views/Points.js

@alexmatz pretty sure we're sticking with Bridge for now, right?

Replace mentions of Multipass

---

src/views/Admin/AdminHome.js

Also took the liberty of lightly modifying the detail copy so it's less repetitive with the primary text here.

Make copy for Arvo keyfile download consistent

---

src/views/Activate/ActivateCode.js
src/views/Activate/PassportVerify.js
src/views/Admin/Reticket/ReticketConfirm.js
src/views/Admin/Reticket/ReticketDownload.js
src/views/Admin/Reticket/ReticketExecute.js
src/views/Admin/Reticket/ReticketVerify.js
src/views/Login/Ticket.js

well that was straightforward. love final-form now that it works (lol)

feat: implement conditional ticket masking following passwordmasking.com's recs

---

src/components/InlineEthereumTransaction.js
src/components/ProgressButton.js
src/lib/useMailer.js
src/views/Invite/InviteEmail.js

+ also solve bug where toString() produces very long float and web3
hates it.

feat: implement progress button for InviteEmail

---

src/lib/trezor.js
src/views/Login/Trezor.js

Fixes #240.
See commits for PR details.

Actually set Trezor HD path on login

---

src/lib/reticket.js
src/lib/tank.js
src/lib/useEthereumTransaction.js
src/views/Invite/InviteEmail.js

Minimum viable fix as currently deployed.
Remaining:

Use BNs for comparisons in tank lib

---

src/store/lib/useRekeyDateStore.js

fix: handle null blockNumber case in rekey date store

---

src/views/Invite/InviteEmail.js

solves #242 
there was no button state for the funding state

fix: stop button from disappearing by adding a button state for waitnng on funding

---

src/form/Inputs.js
src/form/formatters.js
src/form/validators.js
src/lib/validators.js
src/views/Login/PrivateKey.js

feat: hex inputs enforce 0x prefix and private key inputs strip it

---

src/style/bridge.scss
src/style/form-reset.scss

fix: wonky range slider css

---

src/views/Admin/Reticket/ReticketVerify.js

was introduced in the final-form PR 😓 
https://github.com/urbit/bridge/pull/221/files#diff-2678925bd85e1ab74910c92f1a01bb50R32

fix: correct initial value for master ticket in reticket flow

---

src/components/InlineEthereumTransaction.js
src/components/NeedFundsNotice.js
src/views/Activate/PassportTransfer.js
src/views/Admin/Reticket/ReticketExecute.js
src/views/Invite/InviteEmail.js

finally feels good to DRY up this codepath

fix: unify needs funds component and give pending affordance

---

src/views/Invite/InviteEmail.js

https://app.asana.com/0/1130701145004055/1133801057071953/f

fix: make send button have the arrow accessory instead of -/n

---

src/lib/getSuggestedGasPrice.js

Always suggest whole gwei amounts

---

src/components/Buttons.js
src/views/Admin/AdminNetworkingKeys.js
src/views/Point.js

Enable Boot Arvo buttons, link to getting started docs

---

src/components/Greeting.js
src/lib/useWasGreeted.js
src/views/Point.js

The copy here is going to need some serious work, but the code is ready for review.
Clicking dismiss hides the greeting, and sets a cookie so that it's never shown again.
(@shrugs you're still doing the a11y work, so can I still tag you for review also, or would you prefer not?)

Display view-once greeting on Point page

---

src/components/Buttons.js
src/components/MiniBackButton.js
src/components/View.js

If the back button would log you out, it becomes the eject symbol instead of the back-arrow.

Back button for logout

---

src/views/Activate/ActivateCode.js
src/views/Activate/PassportDownload.js
src/views/Activate/PassportVerify.js

Update the app copy to match Figma smackdown.
Would like to update to add bold to text in the verify paragraph, but don't know how. @jyng halp.

Mino copy edits

---

src/views/Point.js

parties -> invite pools

---

package-lock.json
package.json

Update PaperRenderer with new bridge url

---

src/components/Buttons.js
src/lib/metamask.js
src/lib/txn.js
src/lib/wallet.js
src/views/Login.js
src/views/Login/Metamask.js
src/views/Login/Other.js

Adds Metamask authentication to log into bridge.
Metamask doesn't support signing a tx before broadcast, so we "sign" a fake tx
and have metamask sign it upon broadcasting.

Metamask authentication

---

src/components/Passport.js
src/components/SigilDownloader.js
src/lib/SigilDownloader.js
src/views/Point.js

Sigil Download in both SVG and PNG with a black sigil on a white background.

add sigil download on passport

---

src/components/Greeting.js

use galen's copy suggestions

---

src/indigo-react/components/Button.js

Fix tab navigation with indigo react buttons

---

src/form/BridgeForm.js
src/form/SubmitButton.js
src/indigo-react/components/Button.js
src/views/Activate/ActivateCode.js
src/views/Activate/PassportDownload.js
src/views/Activate/PassportVerify.js

Fix submit on enter

---

src/components/SigilDownloader.js

Cleaner sigil image filename

---

src/views/Activate/PassportTransfer.js
src/views/Admin/Reticket/ReticketExecute.js

Updates progress notifications to make clear we're not stealing their money.

Nemesis copy

---

src/views/Point.js

I think this was a regression from https://github.com/urbit/bridge/pull/297

Fix import name of DownloadSigilButton

---

src/lib/keys.js
src/lib/networkCode.js
src/lib/useKeyfileGenerator.js
src/views/Point.js

Allows for the viewing of the login code iff deterministic network keys are used.
Also fixes sigil generation issues.

View +code inside bridge

---

src/lib/error.js
src/lib/txn.js

See also #302. This should banish all "fromWei: pls pass strings or bignums" from existence.
Fixes #306, #310, #316, #318, #319, or at least expose an
underlying issue more clearly.

Bignum 2: fromWei fix

---

src/components/GlobalErrorBoundary.js
src/views/Login.js

Renders on the Login screen like so:
Also includes it in the generated description for error reports.

Include Bridge version number where relevant

---

src/components/Header.js

Fix navigation breadcrumbs to link to urbit.org

Nav breadcrumbs

---

src/Bridge.js
src/components/View.js
src/views/Login.js

Removed nav bar and header and fixed top alignment of card.
cc @galenwp

removed header while we figure out IA and visual alignment

---

src/lib/constants.js
src/lib/tank.js

Walked through the invite flow 10+ times. Noticed a "`.lt` does not exist" error in the console, and hit one transaction that wanted more gas overhead. This should solve both of those, but the mystery errors remain a mystery. ):

Mino tanking

---

src/components/Buttons.js
src/components/Passport.js
src/views/Activate/ActivatePassport.js
src/views/Admin/AdminNetworkingKeys.js
src/views/Invite/InviteEmail.js
src/views/Point.js

Clean up lint warnings, rearranging Point view and change copy

Visual fixes

---

src/views/Admin/AdminNetworkingKeys.js

Trigger New Continuity Era -> Breach Continuity

Individual breach language

---

src/lib/inviteMail.js
src/lib/useMailer.js
src/views/Invite/InviteEmail.js

Closes #338.
(idk how to not get this give the green "this is good" border all the time, but might be fine as-is)
Depends on urbit/onboarding-emails#3.

Allow inclusion of custom message when sending invites

---

src/views/Admin/Reticket/ReticketDownload.js

"Download the thing" isn't quite the level of copy we're aiming at, I don't think. (;

Improve reticket download copy

---

package-lock.json
package.json
src/lib/router.js
src/views/Point.js
src/views/Senate.js

Note that we're leaving out the "get a hash for some text" functionality, since it requires elaboration, and the upcoming vote is on [a pre-determined hash](https://github.com/urbit/azimuth/blob/master/proposals/0xcb1f81e42b5e75f000f94fc71a3ea70cab4bfc6f236b91e717f1b9516e5596b5.txt) anyway.
Will self-merge as @vvisigoth has given approval out of band.

Minimum viable Senate page

---

src/views/Points.js

This seems to have snuck back in at some point.
Fixes #356.

Remove "view point" button

---

src/form/validators.js
src/lib/validators.js
src/lib/wallet.js
src/views/Login/Mnemonic.js
src/views/Senate.js

- Actually validate user-specified derivation paths.
- Fix #355.
- Resolve the "want to use any mnemonic" part of #357, by allowing that if you check a checkbox.
- Sneaks in some clean up of the `Senate.js`, which was spewing hella warnings.

Mnemonic login QoL

---

package-lock.json
package.json

Will quick-merge, as this was tested and approved by @vvisigoth out of band.

Use latest Ledger dependencies

---

src/views/Invite/Email.js

reset email invite after successful submission

---

src/lib/starRelease.js

Fix calculation of details of conditional star release contracts

condSR: fixup available calculation

---

src/views/Point.js

Ensure current user is owner of point before allowing them to send invites
fixes #418

views/point.js: ensure correct perms for invites

---

src/components/LoginButton.js
src/lib/useLocaHosting.js
src/views/UrbitOS/Home.js

Enables one click login by POSTing directly to ${patp}.arvo.network. Requires HTTPS and DNS to be setup. Can one click login into self hosted and remote hosted ships.

One click login

---

src/views/Admin/AdminNetworkingKeys.js

This line was grammatically incorrect.

Fixed small typo

---

src/indigo-react/indigo.css
src/lib/networkCode.js
src/lib/useInviter.js
src/lib/walletgen.js
src/store/lib/useInvitesStore.js
src/store/lib/usePointStore.js
src/store/wallet.js
src/views/Invite/Cohort.js
src/views/Login/Ledger.js
src/views/Login/Metamask.js
src/views/Login/Trezor.js
src/views/Point.js

Adds a deterministic ticket generator. Uses the point and a seed to generate a ticket by hashing the seed and salting with the point to be generated. Using a hash as a deterministic RNG should be fine because we aren't really going deep with the entropy.

wallet-gen: add deterministic invite code generator

---

src/lib/validators.js
src/views/IssueChild.js

issue-child: validate point child relationship

---

src/components/MaybeSigil.js
src/lib/metamask.js
src/lib/txn.js
src/lib/useRouter.js
src/views/Residents.js
src/views/UrbitOS/Home.js

some fixes: 
txn: always throw an Error on failure
sigil: check patp has sigil before render
residents: fix broken crumb navigation
fixes: #478 #481 #480 #344 #479 #484

various bridge cleanup

---

src/components/Passport.js

Fixes #496

---

src/views/UrbitID.js
src/views/UrbitOS.js

Bruh the back buttons don't work.

urbit-os, urbit-id: fix non-functional back button

---

src/lib/starRelease.js

For linear releases, this was causing us false positives on the "does
this address have a lockup" check. Subsequently calling the withdrawe
limit function for an address without a lockup would result in a
contract-side exception being thrown due to the division by zero. This
exception wasn't getting handled properly, and prevented users with
conditional lockups from actually viewing those in Bridge.
So now we make sure to diligently convert received values into actual
integers, instead of the strings we get them as.
For conditional releases, this wasn't actively causing any problems
(that we were aware of), but we make similar changes there anyway,
for peace of mind.

star release: fix string<->int shenanigans

---

package.json
src/Bridge.js
src/lib/flags.js
src/lib/utils/address.ts

dx: add `pilot-mainnet` script

---

package-lock.json
package.json
src/lib/useRoller.ts

useRoller: get unspawned points from roller-api

---

src/components/L2/Dropdowns/AccountsDropdown.tsx
src/components/L2/LayerIndicator.scss
src/lib/useRoller.ts
src/store/lib/useControlledPointsStore.js
src/views/Point/MigrateL2.tsx
src/views/Point/Point.js

These are updates to the Layer 2 planet invite spawning process

Updating the spawn invite flow

---

src/lib/getSuggestedGasPrice.js

Instead of ethgasstation, which tends to overshoot by a lot.
This is an 80/20 fix for #555. The more complex solution proposed there may or may not still be worth doing in the future, but for the time being simply switching over to Etherscan should give us a lot more reliable suggestions.

lib: get gas prices from etherscan

---

package.json
src/components/L2/Dropdowns/AccountsDropdown.tsx
src/components/NetworkingKeys.js
src/lib/types/L1Point.ts
src/lib/useHasNetworkKeysSet.tsx
src/lib/useRoller.ts
src/lib/useSeenMissingKeys.js
src/lib/utils/nonce.ts
src/lib/utils/roller.ts
src/store/lib/useDetailsStore.js
src/store/lib/useDetailsStore.ts
src/store/lib/useRekeyDateStore.js
src/store/roller.ts
src/views/Activate/MasterKeyTransfer.tsx
src/views/Login/Ticket.js
src/views/Point/InviteForm.tsx
src/views/Point/Point.js
src/views/Point/Point.scss
src/views/Point/Point.tsx
src/views/Points.js

We did some testing of the new invite flow in `bridge-dev` and identified a few issues. This PR addresses them so we can continue performing QA for L2.
- improved handling and storage of nonces
- network keys: fix deriving and configuration
- refactor Point view to improve component lifecycle management

invites: various improvements to Invite flow and Point view

---

DEVELOPMENT.md
src/style/fadeable.scss
src/views/Activate/ActivateCode.tsx
src/views/Activate/MasterKey.tsx
src/views/Activate/MasterKeyConfirm.tsx
src/views/Activate/MasterKeyDownload.tsx
src/views/Activate/MasterKeyReveal.tsx
src/views/Activate/MasterKeyTransfer.tsx

- add Back button to Confirm page
- tweak animation timing of master key reveal
- reduce view inset
- prevent double fade-ins

ui: address Design feedback for Activate Invite flow

---

src/form/Inputs.js
src/views/Activate/ActivateParagraph.tsx
src/views/Activate/ActivateView.tsx
src/views/Activate/MasterKeyConfirm.tsx
src/views/Activate/MasterKeyDownload.tsx

- border-radius to 8px
- activate flow copy uses 14px
- limit confirm inputs to 6 characters
- skip fade in when going back from Confirm to Download
fixes #688, fixes #689, fixes #691, fixes #692

invite-ui: address Design feedback

---

DEVELOPMENT.md
src/components/L2/Headers/L2PointHeader.tsx
src/lib/constants.ts
src/views/Transactions/TransactionHistory.tsx

- Sort TXs by point size (galaxy --> star --> planet)
- When navigating to TX history view from Point view, pre-filter the
results by selected point
- Also add support for additional TX events
- `adopt`, `cancel-escape`,  `escape`, `detach`, `reject`, `set-management-proxy`
fixes #687, fixes #690, fixes #697

 tx-ui: address Design feedback

---

package-lock.json
package.json
src/lib/constants.ts

This updates the placeholder TX event labels with clearer copy for end users, and adds updated Indigo icons.

tx-view: update TX history event labels & icons

---

src/views/Point/IssueChild.tsx

This change hides the button when the TX is ready for sending.

invite-ux: fix address button behavior

---

src/views/Ops/Ops.scss
src/views/Ops/Ops.tsx

ops-ui: address Design feedback

---

.github/ISSUE_TEMPLATE/l2-bug-report.md

Adds an issue template for our December 2021 QA effort.

bridge: add L2 QA issue template

---

src/lib/constants.ts

- add `set-spawn-proxy icon`
*Spawn Proxy Changed event icon*

tx-ui: add set-spawn-proxy icon

---

src/components/Buttons.js
src/components/InlineEthereumTransaction.js
src/views/Party/PartySetPoolSize.js
src/views/Point/MigrateL2.scss
src/views/Point/Point.scss
src/views/Point/UrbitOS.js
src/views/UrbitOS/Home.tsx
src/views/UrbitOS/NetworkKeys.scss
src/views/UrbitOS/NetworkKeys.tsx

Network keys redesign

---

src/components/L2/Headers/L2PointHeader.scss
src/components/L2/Headers/L2PointHeader.tsx
src/components/L2/PendingTransaction.scss
src/components/L2/PendingTransaction.tsx
src/components/L2/PermissionIndicator.scss
src/components/L2/PermissionIndicator.tsx
src/components/L2/PointList.tsx
src/lib/getSuggestedGasPrice.js
src/lib/proxy.js
src/lib/router.js
src/lib/types/PendingL1Transaction.ts
src/lib/types/Point.ts
src/lib/useRoller.ts
src/store/rollerStore.ts
src/views/AcceptTransfer.tsx
src/views/CancelTransfer.js
src/views/Point/IssueChild.tsx
src/views/Point/MigrateL2.tsx
src/views/Point/Point.scss
src/views/Point/Point.tsx
src/views/Points.tsx
src/views/UrbitID/SetProxy.js
src/views/UrbitOS/ChangeSponsor.js
src/views/UrbitOS/NetworkKeys.tsx

Example in issue: https://github.com/urbit/bridge/issues/823

Added pending L1 transaction indicators

---

src/components/InlineEthereumTransaction.js
src/components/InlineEthereumTransaction.scss
src/components/L2/Headers/L2BackHeader.tsx
src/store/rollerStore.ts

The screen:
@jyng @tomholford @nerveharp

Changed button state when insufficient ETH

---

src/components/L2/Dropdowns/FeeDropdown.scss
src/components/L2/Dropdowns/FeeDropdown.tsx
src/style/shared/variables.scss

Polish custom gwei dropdown

---

src/lib/useRoller.ts
src/views/Invite/Cohort.scss
src/views/Invite/Cohort.tsx

Add invite limit message on Invites page

---

src/style/master-key.scss

Add explicit height to master key animation

---

src/components/L2/Modal.scss
src/components/L2/Modal.tsx
src/views/Activate/MasterKeyReveal.tsx
src/views/Invite/Cohort.scss
src/views/Invite/Cohort.tsx

Download CSV modal

---

src/assets/blank-planet-sigil.svg
src/components/L2/Window/Window.scss
src/components/L2/Window/Window.tsx
src/components/View.js
src/components/form/TicketInputAccessory.scss
src/components/form/TicketInputAccessory.tsx
src/form/Inputs.tsx
src/lib/useBreakpoints.js
src/lib/useBreakpoints.tsx
src/lib/validators.ts
src/style/master-key.scss
src/views/AcceptTransfer.tsx
src/views/Activate/ActivateCode.tsx
src/views/Activate/ActivateCodeForm.tsx
src/views/Activate/ActivateMasterKey.tsx
src/views/Activate/ActivateView.scss
src/views/Activate/ActivateView.tsx
src/views/Activate/MasterKeyConfirm.scss
src/views/Activate/MasterKeyConfirm.tsx
src/views/Activate/MasterKeyDownload.tsx
src/views/Activate/MasterKeyReveal.tsx
src/views/Activate/MasterKeyTransfer.tsx
src/views/Login/Hardware.js
src/views/Login/Ledger.tsx
src/views/Login/LoginSelector.scss
src/views/Login/Ticket.tsx

Activate design updates

---

src/lib/validators.ts
src/views/CancelTransfer.tsx
src/views/Login/LoginSelector.scss
src/views/Login/LoginSelector.tsx
src/views/Ops/Residents.scss

Update login design for metamask and walletconnect

---

src/views/Invite/Cohort.tsx

invites: s/planet/invite

---

public/index.html

bridge: scrub bogus text from index

---

src/views/Ops/Ops.tsx

galaxy ops: add conditional point subtext

---

src/views/Login/Ticket.tsx

login: toggles shards or master ticket

---

package-lock.json
package.json
src/lib/utils/roller.ts
src/store/lib/useControlledPointsStore.js
src/store/network.js

This potentially fixes #957 using the same solve as #647. It also makes an attempt to prevent the "execution reverted" issue seen on login when you have the MM extension installed.

roller: personal sign issue

---

src/lib/types/Point.ts
src/lib/useRoller.ts
src/views/Invite/Cohort.tsx

This should clear up some of the confusion around quotas.

quota: swaps generic quota for actual allowance, fixes quota reset time

---

src/components/Greeting.js

Greeting: fix link to urbit.org
